name: Flyway Database Migration

on: push

jobs:
  migrate:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: devops_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U admin -d devops_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Flyway migrations
        uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: jdbc:postgresql://postgres:5432/devops_db
          user: admin
          password: secret
          locations: filesystem:./migrations
